### ISSUE TITLE
Missing error standza

### ISSUE THREAD

**Issue by fabricedesre** [mozilla-services/remote-worker-server#4]
If the headless gecko can't fetch the source worker or fails to load it, it will return an error message.
I'm currently sending : { error: "disconnect",
                                      workerId: "..." } 
but that is not handled by the python side.

**Comment by Natim** [comment]
Ok, can we answer a "worker-error" message type with a action: "error" and a reason: "impossible to fetch the code"

    {
        "messageType": "worker-error",
        "action": "error",
        "errno": 107,
        "reason": "impossible to fetch the worker code."
    }

We should start a list of errcode as well. Do you have a list of what could happen yet?

**Comment by fabricedesre** [comment]
That works for me. I'll you know the error codes as I add error cases. For now I have:
- unable to fetch the resource.
- syntax error in the worker code.
- uncaught exception when running the worker.

**Comment by Natim** [comment]
Fixed on https://github.com/mozilla-services/remote-worker-server/commit/da555473a69600b5512ab353d85ca0b2181b8b4a
